### ISSUE TITLE
when installing with MySQL The provided value for the column is too long for the column's type. Column: storefrontToken

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#22]
The provided value for the column is too long for the column's type. Column: storefrontToken
    at cb (/var/www/html/stripe_foundations/node_modules/@prisma/client/runtime/index.js:36494:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DisplaySettingController.run (webpack-internal:///(api)/./src/pages/api/store/display-settings/put.ts:135:5)
    at async Array.func (webpack-internal:///(api)/./backend/controllers/api-route-controller.ts:155:26) {
  code: 'P2000',
  clientVersion: '2.30.3',
  meta: { column_name: 'storefrontToken' }

prisma issue with MySQL
  
  https://github.com/prisma/prisma/discussions/4079

**Comment by huntario** [comment]
Hunter, with BigCommerce here again. Thanks so much for the context with the Prisma issue ( . I’ve looked into this with the information provided and I think it should be as simple as adding the data type within prisma > schema.prisma : Store

`storefrontToken                 String?         @db.Text`

prisma.io/docs/concepts/components/prisma-schema/data-model#native-types-mapping

I’ll need to test this out a bit and consider any ramifications it might have. Have you found a solution that works for you? I’ll PR a fix. Thanks again for noticing this.

**Comment by huntario** [comment]
The fix for this has been merged in the PR above. If you are still having this problem after rebasing to the latest.
